name: 

on:
  push:
    paths:
      - docker-build/
    branches:
      - main

  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: mendelsh/mendel-batel-oct

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set tag with date and time
        id: vars
        run: echo "TAG=$(date +'%d-%m-%y-%H-%M')" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$TAG
